services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/Fromundus/drrs-api
    region: oregon
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
    healthCheckPath: /
    autoDeploy: true
